# https://taskfile.dev

version: '3'

tasks:
  new-control:
    desc: Creates a new control
    interactive: true
    cmds:
      - ./.scripts/new-control.sh
  new-view:
    desc: Creates a new view
    interactive: true
    cmds:
      - ./.scripts/new-view.sh
  run:
    desc: Builds and runs the application
    cmds:
      - dotnet run --project src/Xabbo.Avalonia
  pack:
    desc: Packages the extension
    cmds:
      - bash ./.scripts/pack.sh

